/************************************************************************************
 *
 * Assignment 1
 * Author: Drew Medlock
 * KUID: 3152931
 * File Created: 9/1/2026
 * File Description: Main file that provides the extractIPv4 function and main loop.
 *
 ***********************************************************************************/
// These imports are from the standard library
#include <cstddef>
#include <iostream>
#include <ostream>
#include <string>
/*
 * This function has been generated by GPT-6 Astra
 * AI generated comments have been stripped out, and replaced with my understanding of the function.
 */
bool extractIPv4(const std::string& str, unsigned long& outAddress, int& outPort)
{
    /*
     * The control flow of this function:
     *  * For each character the function attempts to go on a "run" of valid tokens
     *  * It then attempts to break this run into 4 parts for the ip address
     *  * If there is a ':' present, it attempts to read a port address from the end of the run of tokens
     * For checking if it is a digit, it does this with the ascii values of the numbers
     * For checking if it is a token, it reuses the previous function, and checks for '.' and ':' specifically.
     * For converting between chars to int, it subtracts the base ascii value of the numbers away then shifts the
     * accumulating number in base 10, and adds the decimal number to the int with a static cast
     * For validation it checks for 4 octets of 3 maximum digits, with a max value of 255. If it starts with a 0, it must be length 1
     */
    // These set the default values of the 2 input values for returning if nothing matches.
    outAddress = 0;
    outPort = -1;
    // This lambda function is a AI written function that uses the ASCII value of inputs to determine if a character is a
    // digit 0-9
    const auto isDigit = [](char c) {
        return c >= '0' && c <= '9';
    };
    // This lambda function identifies if a character is something we are paying attention to, a digit, ., or :.
    const auto isTokenChar = [&](char c) {
        return isDigit(c) || c == '.' || c == ':';
    };
    // This for loop iterates through the whole length of the string, and is where the processing takes place
    for (std::size_t i = 0; i < str.size();) {
        // If the character isn't a token, then we just pass by it and move onto the next loop
        if (!isTokenChar(str[i])) {
            ++i;
            continue;
        }
        // This code attempts to go on a "run" where each item is a token, and records the start and end
        const std::size_t begin = i;
        while (i < str.size() && isTokenChar(str[i]))
            ++i;
        const std::size_t end = i;
        std::size_t pos = begin;

        // This is a lambda function that captures the external variables
        const auto readNumber = [&](std::size_t maxDigits,
                                    unsigned limit, unsigned& value) {
            // maxDigits is a number for how many digits, while limit is a cap on the value of the number
            const std::size_t start = pos;
            value = 0;
            // Will process all digits until the end or a none digit character
            while (pos < end && isDigit(str[pos])) {
                // If the max Digit length is exceeded it immediately returns false, showing invalid
                if (pos - start >= maxDigits)
                    return false;
                // This is the logic for manually processing a digit from a string
                // It takes a digit from the string subtracts out the ascii base using '0' and then adds it to the value
                // It also increases the magnitude of value with the additional digit
                // pos++ increments pos after accessing the value from the string
                value = value * 10 +
                        static_cast<unsigned>(str[pos++] - '0');
                // A quick check to make sure that the number is bigger than a given limit for example 255
                if (value > limit)
                    return false;
            }
            // This guarantees that the length is greater than 0, and that the string doesn't have a leading 0
            // It does this by checking if the start is a 0, and it if it the length must be 1
            return pos > start &&
                   (pos - start == 1 || str[start] != '0');
        };
        
        unsigned long address = 0;
        bool valid = true;
        // This is a for loop that will run 4 times if the address is correctly formed, processing the ip addr in
        // octet parts
        for (int part = 0; part < 4; ++part) {
            unsigned octet;
            // It attempts to read the next 3 numbers from the input for an octet of the ip addr
            if (!readNumber(3, 255, octet)) {
                valid = false;
                break;
            }

            // After reading the octet it shifts the address over by 8 bits then puts the octet in
            address = (address << 8) | octet;
            // If the part isn't the last (fourth) part, then the pos index must be pointing to a ., or the run is invalid
            if (part < 3) {
                if (pos == end || str[pos] != '.') {
                    valid = false;
                    break;
                }
                ++pos; // Increments to start reading the next part
            }
        }
        // If this string wasn't valid then it continues to the next character to start at
        if (!valid)
            continue;
        // This now attempts to read the port if there is an : at the end of the 4 octets.
        int port = -1;
        if (pos < end && str[pos] == ':') {
            ++pos;
            unsigned parsedPort;

            if (!readNumber(5, 65535, parsedPort))
                continue;

            port = static_cast<int>(parsedPort);
        }
        // If the position after reading the port still is not at the end, it isn't valid and it goes to the next char
        if (pos != end)
            continue;

        // Sets the variables put in by reference to the first address and port that was read in, then returns true
        outAddress = address;
        outPort = port;
        return true;
    }
    // If the loop doesn't identify any valid addresses it will return false with the values set as 0, and -1
    return false;
}

#ifndef TESTING // ifndef blocks were suggested by Google Gemini 3.8 Flash Extended
// Main function was written by Me, change from std::cin to std::getline() was suggested by ChatGPT-6 Astra, as well as changes to the loop
int main() {
    std::string input;
    unsigned long address;
    int port;
    while (true) {
        std::cout << "Enter a string (or 'END' to quit): ";
        if (std::getline(std::cin, input) || input == "END") {
            break;
        }
        if (extractIPv4(input, address, port)) {
            std::string port_string; // If there is a port number we need to convert it to a string or None
            (port == -1) ? port_string = "none" : port_string = std::to_string(port);
                                                                // number-to-string functions aren't banned
            unsigned int mask = 0xFF; // is eight 1's bit at end of int for extracting 8 bits from the decimal
            // This just shifts the bits to the right to align them with the 0xFF to cap the numbers off to 255 for IPv4
            unsigned int a = (address >> 24) & mask;
            unsigned int b = (address >> 16) & mask;
            unsigned int c = (address >> 8)  & mask;
            unsigned int d =  address        & mask;
            std::cout << "Extracted IPv4 address: " <<  a << '.' << b << '.' << c << '.' << d \
                      << " (decimal value: " << address << ", port: " << port_string << ")" << std::endl;
        }
        else {
            std::cout << "Invalid input: no valid IPv4 address found" << std::endl;
        }
    }
    std::cout << "Program terminated." << std::endl;
    return 0;
}
#endif