/************************************************************************************
 *
 * Assignment 1
 * Author: Drew Medlock
 * KUID: 3152931
 * File Created: 9/1/2026
 * File Description: Main file that provides the extractIPv4 function and main loop.
 *
 ***********************************************************************************/
// These imports are from the standard library
#include <cstddef>
#include <iostream>
#include <ostream>
#include <string>
/*
 * This function has been generated by GPT-6 Astra
 * AI generated comments have been stripped out, and replaced with my understanding of the function.
 */
bool extractIPv4(const std::string& str, unsigned long& outAddress, int& outPort)
{
    // These set the default values of the 2 input values for returning if nothing matches.
    outAddress = 0;
    outPort = -1;
    // This lambda function is a AI written function that uses the ASCII value of inputs to determine if a character is a
    // digit 0-9
    const auto isDigit = [](char c) {
        return c >= '0' && c <= '9';
    };

    const auto isTokenChar = [&](char c) {
        return isDigit(c) || c == '.' || c == ':';
    };

    for (std::size_t i = 0; i < str.size();) {
        if (!isTokenChar(str[i])) {
            ++i;
            continue;
        }

        const std::size_t begin = i;
        while (i < str.size() && isTokenChar(str[i]))
            ++i;
        const std::size_t end = i;
        std::size_t pos = begin;

        const auto readNumber = [&](std::size_t maxDigits,
                                    unsigned limit, unsigned& value) {
            const std::size_t start = pos;
            value = 0;

            while (pos < end && isDigit(str[pos])) {
                if (pos - start >= maxDigits)
                    return false;

                value = value * 10 +
                        static_cast<unsigned>(str[pos++] - '0');

                if (value > limit)
                    return false;
            }

            return pos > start &&
                   (pos - start == 1 || str[start] != '0');
        };

        unsigned long address = 0;
        bool valid = true;

        for (int part = 0; part < 4; ++part) {
            unsigned octet;
            if (!readNumber(3, 255, octet)) {
                valid = false;
                break;
            }

            // Pack the first octet into the most significant byte.
            address = (address << 8) | octet;

            if (part < 3) {
                if (pos == end || str[pos] != '.') {
                    valid = false;
                    break;
                }
                ++pos;
            }
        }

        if (!valid)
            continue;

        int port = -1;
        if (pos < end && str[pos] == ':') {
            ++pos;
            unsigned parsedPort;

            if (!readNumber(5, 65535, parsedPort))
                continue;

            port = static_cast<int>(parsedPort);
        }

        if (pos != end)
            continue;

        // Return the first valid complete token.
        outAddress = address;
        outPort = port;
        return true;
    }

    return false;
}

#ifndef TESTING // ifndef blocks were suggested by Google Gemini 3.8 Flash Extended
// Main function was written by Me
int main() {
    std::string input;
    unsigned long address;
    int port;
    while (input != "END") {
        std::cout << "Enter a string (or 'END' to quit): ";
        std::cin >> input;
        if (input == "END") {
            continue;
        }
        else {
            if (extractIPv4(input, address, port)) {
                std::string port_string; // If there is a port number we need to convert it to a string or None
                (port == -1) ? port_string = "none" : port_string = std::to_string(port);
                                                                    // number-to-string functions aren't banned
                unsigned int mask = 0xFF; // is eight 1's bit at end of int for extracting 8 bits from the decimal
                unsigned int a = (address >> 24) & mask;
                unsigned int b = (address >> 16) & mask;
                unsigned int c = (address >> 8)  & mask;
                unsigned int d =  address        & mask;
                std::cout << "Extracted IPv4 address: " <<  a << '.' << b << '.' << c << '.' << d \
                          << " (decimal value: " << address << ", port: " << port_string << ")" << std::endl;
            }
            else {
                std::cout << "Invalid input: no valid IPv4 address found" << std::endl;
            }
        }
    }
    std::cout << "Program terminated." << std::endl;
    return 0;
}
#endif